/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebars: [
    "quick_start",
    {
      type: "category",
      label: "Morpheme CLI",
      items: [
        {
          type: "autogenerated",
          dirName: "morpheme_cli", // Generate sidebar slice from docs/api
        },
      ],
    },
    {
      type: "category",
      label: "Starter Kit",
      items: [
        {
          type: "autogenerated",
          dirName: "starter_kit", // Generate sidebar slice from docs/api
        },
      ],
    },
    {
      type: "category",
      label: "Morpheme Library",
      items: [
        {
          type: "autogenerated",
          dirName: "morpheme_library", // Generate sidebar slice from docs/api
        },
      ],
    },
  ],
};

module.exports = sidebars;
